### ISSUE TITLE
0.6.0 Attempting to Load Every File in /relations as a Relation

### ISSUE THREAD

**Issue by ylg** [rom-rb/rom-rails#57]
For example, I've relations/archivable_queries.rb that looks like so:

```
module ArchivableQueries
  def list(options = {archived: false})
    where(archived: options[:archived])
  end
end
```

This is included in various relations. This worked in 0.5.0. However in 0.6.0, rom attempts to load the module as a relation and throws a NoMethodError because ArchivableQueries doesn't define #gateway.

I put together a commit for a little clearer errors that may help understand what I'm getting at:
https://github.com/sensedata/rom/commit/a0edcc3aa47f3b1858be7be07954078ee2c5f1d7

With that code in and the following config:

```
config.gateways[:default] = [:sql, database_url, encoding: 'unicode']
```

I then see:

```
rom/lib/rom/setup/finalize.rb:135:in `rescue in block in infer_relation?': Cannot infer relation for schema_info with ArchivableQueries; undefined method `dataset' for ArchivableQueries:Module. (RuntimeError)
```

With inference off, as in:

```
config.gateways[:default] = [:sql, database_url, encoding: 'unicode', infer_relations: false]
```

I then see:

```
rom/lib/rom/setup/finalize/relations.rb:31:in `rescue in block in run!': Cannot finalize relation class ArchivableQueries; undefined method `gateway' for ArchivableQueries:Module. (RuntimeError)
```

Whether the fix should be to skip non-relation classes and modules (e.g., by checking if they respond to an essential method such as #gateway) as it seemed in 0.5.0, or throwing a more helpful error (e.g., "you put your non-relation class in my relation dir!"), or something else, I don't know. The current state is problematic.
##

**Comment by ylg** [comment]
The behavior appears to be somewhat shared by commands, though the root cause may be a bit different. While in earlier versions the documented approach to commands was:

    module CategoryCommands
      class Create < ROM::Commands::Create[:sql]
        relation :categories
        register_as :create
        result :one
      end

      class Update < ROM::Commands::Update[:sql]
        relation :categories
        register_as :update
      end

      class Delete < ROM::Commands::Delete[:sql]
        relation :categories
        register_as :delete
      end
    end

This will cause an error because rom now attempts to load the module CategoryCommands as a command, rather than the classes inside.

**Comment by solnic** [comment]
We no longer use inherited hook to auto-register commands in a global setup object, the auto-registration used by rom-rails needs one-class-per-file in order to work. As far as the main issue goes - we should be skipping anything that's not a rom component, so I think it's a bug that should be fixed, and it's in the rom core codebase.

**Comment by ylg** [comment]
Sorry, I debated where to file this but as seemed to me like rom-rails would be the one responsible for handing off a clean list of relations/mappers/commands to rom, I ended up here. Skipping would be nice, though whatever the case, some sort of logging or contextual info in the errors would be fantastic, e.g., https://github.com/sensedata/rom/commit/a0edcc3aa47f3b1858be7be07954078ee2c5f1d7 Thanks for looking at this!

**Comment by solnic** [comment]
@ylg no worries, I mentioned where the responsible code is just FYI :)

To be honest, my fix would be to skip the non-rom-component classes but warn about it, these dirs should really only include the rom components. Do you think it would be too pedantic?

**Comment by ylg** [comment]
I think that's just fine. If it were I'd just mimic whatever Rails does if someone drops a Module file into /controllers or /jobs (I think that's skip and no-warn.) But, for me, even errors would be fine, so long as one could infer the _why_ of them.

**Comment by solnic** [comment]
@endash any opinions on silently skipping non-rom components while auto-registering?

**Comment by endash** [comment]
@solnic I have no qualms silently skipping things we vacuum up that don't actually descend from a ROM component. In simpler circumstances duck typing might be a concern, but when it comes to the components ROM is omakase. *runs away with arms flailing wildly* Our concern is just that our components, and nothing else, be registered, not enforcing the purity of some organization convention.

**Comment by cflipse** [comment]
Is this still a concern, or did we fix in rom core?  @solnic

**Comment by cflipse** [comment]
closing due to inativity
