### ISSUE TITLE
0.6.0 not working with spring 1.7.1

### ISSUE THREAD

**Issue by ryanmtaylor** [rom-rb/rom-rails#59]
Using the current versions of `rom-rails` (0.6.0) and `rom-sql` (0.7.0) along with `spring` (1.7.1) I get the following error ONLY when using spring:

```
.../gems/rom-1.0.0/lib/rom/container.rb:125:in `each_key': undefined method `disconnect' for :default:Symbol (NoMethodError)
```

However, it works fine when I run e.g. `DISABLE_SPRING=true rails c`

Also, `spring stop` does not solve the issue.
##

**Comment by ryanmtaylor** [comment]
I fixed it by renaming my initializer `_rom.rb` so it loaded earlier.  This project was more or less a default rails project, but I used rails-composer to create it.

Here is a list of my initializers.

```
_rom.rb
backtrace_silencers.rb
filter_parameter_logging.rb
mime_types.rb
assets.rb
cookies_serializer.rb
inflections.rb
session_store.rb
wrap_parameters.rb
```

**Comment by cflipse** [comment]
That's ... strange.  Once you're in initializers, the load order really only matters if it's clashing with other initializers.

Would you mind 1) re-verifying this, and 2) posting a sample project that reproduces this?
